#include "stdafx.h"

#include "Framework\Util\Utility.cpp"
#include "Framework\ThreadPool\GdsThreadPool.cpp"
#include "Framework\Logger\output_logger.cpp"
#include "Framework\PerformanceCheck\Performance.cpp"
#include "Component\ComVisual\GdsComVisual.cpp"
#include "Component\ComAnimation\GdsComMoveable.cpp"
#include "Renderer\GdsRendererBase.cpp"
#include "Renderer\GdsRenderObject.cpp"
#include "ResourceManager\Type\GdsPixelshader.cpp"
#include "ResourceManager\Type\GdsVertexShader.cpp"
#include "Terrain\GdsTerrain_Triangle.cpp"
