#include "stdafx.h"

#include "Framework\FileSystem\GdsFile.cpp"
#include "Framework\ThreadPool\GdsThread.cpp"
#include "Framework\Logger\logger.cpp"
#include "Framework\InputSystem\GdsMouse.cpp"
#include "Component\GdsComponentMaker.cpp"
#include "Component\ComAnimation\GdsComAnimationFamily.cpp"
#include "Camera\GdsFrustum.cpp"
#include "Renderer\GdsRenderFrame.cpp"
#include "ResourceManager\Type\GdsIndexBuffer.cpp"
#include "ResourceManager\Type\GdsVertexBuffer.cpp"
#include "Terrain\GdsTerrain_Tile.cpp"
