#include "stdafx.h"

#include "Framework\ThreadPool\GdsSyncCriticalSection.cpp"
#include "Framework\Logger\console_logger.cpp"
#include "Framework\InputSystem\GdsInputSystem.cpp"
#include "GameObject\GdsGameObject.cpp"
#include "Component\ComVisual\GdsComVisualMesh.cpp"
#include "Camera\GdsCamera.cpp"
#include "Renderer\GdsRendererDX9.cpp"
#include "Renderer\GdsRenderStateGroup.cpp"
#include "ResourceManager\Type\GdsResBaseType.cpp"
#include "Scene\GdsNode.cpp"
#include "MemObject\GdsMemObject.cpp"
